# R wrapper for the exact event-driven network SIR (net_sir_events.cpp).
#
# Drop-in alternative to run_stoch_adj() for the NETWORK model: same process,
# simulated exactly (no dt bias) in O(E log V) instead of O(n * max_degree)
# per dt step.
#
# Validity: time-homogeneous rates (scalar beta, constant gamma), waning = 0.
#
#   source("net_sir_events.R")   # compiles on first use

if (!requireNamespace("cpp11", quietly = TRUE))
  stop("net_sir_events.R needs the 'cpp11' package")

# The source file sits next to this script; resolve it so the simulator can be
# used from a subdirectory (slurm jobs, tests with chdir=TRUE) and not only
# from the project root. odin_project_root() is defined in odin_cache.R and is
# already loaded whenever stoch_model.R is.
.net_sir_cpp_path <- function() {
  cand <- "net_sir_events.cpp"
  if (file.exists(cand)) return(cand)
  if (exists("odin_project_root", mode = "function")) {
    p <- file.path(odin_project_root(), "net_sir_events.cpp")
    if (file.exists(p)) return(p)
  }
  stop("cannot locate net_sir_events.cpp (looked in ", getwd(), ")")
}

# Compile once per session (cheap: a single translation unit).
# cpp_source() injects the generated R wrapper into `env` and returns a
# DLLInfo, so take the function out of the environment rather than off the
# return value.
.net_sir_env <- new.env(parent = globalenv())
net_sir_compile <- function(force = FALSE) {
  if (!force && !is.null(.net_sir_env$net_sir_event_times))
    return(invisible(.net_sir_env$net_sir_event_times))
  # OpenMP must be requested explicitly: cpp_source does not add it, and
  # without it the realisation loop runs single-threaded.
  old <- Sys.getenv(c("PKG_CXXFLAGS", "PKG_LIBS"), unset = NA)
  Sys.setenv(PKG_CXXFLAGS = "-fopenmp", PKG_LIBS = "-fopenmp")
  on.exit({
    for (v in names(old))
      if (is.na(old[[v]])) Sys.unsetenv(v) else do.call(Sys.setenv, setNames(list(old[[v]]), v))
  }, add = TRUE)
  cpp11::cpp_source(.net_sir_cpp_path(), env = .net_sir_env, quiet = TRUE)
  if (is.null(.net_sir_env$net_sir_event_times))
    stop("net_sir_event_times was not registered by cpp11::cpp_source()")
  invisible(.net_sir_env$net_sir_event_times)
}

# Contact matrix (or an existing adjacency list from contact_matrix_to_adj)
# -> 0-based CSR in the TRANSMIT direction.
#
# Direction matters: get_conact_matrix_pl returns an ASYMMETRIC (directed)
# matrix. In stoch_mod_adj.R the FOI on node i sums over neighbors[, i], i.e.
# row i lists who infects i -- a RECEIVE list. The event-driven simulator
# walks outward from an infectious node, so it needs the transpose: who node k
# can infect, = {i : k in recv(i)} = column k. Using the receive list to
# transmit silently simulates the reversed graph.
adj_to_csr <- function(contact_matrix = NULL, adj = NULL) {
  if (is.null(adj)) {
    n    <- nrow(contact_matrix)
    recv <- lapply(seq_len(n), function(i) which(contact_matrix[i, ] != 0))
  } else {
    n    <- ncol(adj$neighbors)
    recv <- lapply(seq_len(n), function(i) {
      k <- which(adj$mask[, i] == 1L)
      if (!length(k)) integer(0) else as.integer(adj$neighbors[k, i])
    })
  }
  # Transpose recv -> transmit: edge (k infects i) for each i, k in recv[[i]].
  to    <- rep.int(seq_len(n), lengths(recv))          # i (receiver)
  from  <- as.integer(unlist(recv, use.names = FALSE)) # k (transmitter)
  ord   <- order(from, method = "radix")
  deg   <- tabulate(from, nbins = n)
  list(n   = n,
       nbr = as.integer(to[ord]) - 1L,                 # 0-based receivers
       ptr = as.integer(c(0L, cumsum(deg))))
}

# Returns a data.table matching run_stoch_network()'s output: time, sim,
# C1 (cumulative unvaccinated cases), C2 (cumulative vaccinated cases).
#
# `beta` is on the SAME scale run_stoch_adj receives, i.e. run_stoch_network
# has already multiplied the user's beta by N / k_mean.
#
# The graph can be given as a pre-built CSR (`csr`, cheapest -- build it once
# per network with adj_to_csr), as an adjacency list, or as a contact matrix.
#
# count_seeds=FALSE drops the I_ini index cases from C1/C2. That is what makes
# this a drop-in for run_stoch_network: stoch_mod_adj.R has initial(C[]) <- 0,
# so dust counts only cases generated by transmission, whereas the event
# simulator records inf = 0 for every seed. Counting them would add a constant
# +I_ini to the totals -- ~10% of the target counts in the small-N configs.
run_stoch_network_events <- function(beta, N, susceptibility = c(1, 1),
                                     t, vac, csr = NULL, gamma = 1,
                                     timepoints = NULL, I_ini = 2,
                                     transmissibility = NULL,
                                     n_sim = 100, seed = NULL, k_mean = 6,
                                     cores = 1L, adj = NULL, c_ij = NULL,
                                     count_seeds = FALSE,
                                     return_times = FALSE,
                                     random_seeds = TRUE) {
  net_sir_compile()
  if (is.null(csr)) {
    if (is.null(adj) && is.null(c_ij))
      stop("run_stoch_network_events needs one of csr, adj or c_ij")
    csr <- adj_to_csr(contact_matrix = c_ij, adj = adj)
  }
  if (is.null(timepoints)) timepoints <- seq(1, t, 1)
  n <- csr$n
  # A length-n vector is used as the per-node susceptibility directly; the
  # 2-vector form is the usual (control, vaccinated) shorthand. The per-node
  # form is what lets the contact-dependent-vaccine-effect model run on this
  # engine, since its alpha_eff is just a precomputable vector.
  sus <- if (length(susceptibility) == n) as.numeric(susceptibility) else {
    s0 <- rep(susceptibility[1], n); s0[vac] <- susceptibility[2]; s0 }
  tr  <- if (is.null(transmissibility)) rep(1, n) else transmissibility
  # Index cases. random_seeds = TRUE draws I_ini distinct nodes afresh in EVERY
  # realisation (in C++, from that realisation's own stream). The alternative --
  # and what this did originally -- is to seed the first I_ini nodes, the same
  # ones every time, which makes the whole outbreak conditional on whether those
  # particular nodes happen to be hubs. On a heavy-tailed graph that dominates:
  # diag_seed_fizzle.R found P(no epidemic) running from 0.44 to 0.69 across
  # four networks at I_ini = 3, and at I_ini = 1 two of four networks never took
  # off at all. Randomising makes the fizzle probability a property of the
  # structure rather than of node ordering.
  #
  # Reproducibility is unaffected: the draw uses the per-realisation stream
  # keyed on the realisation index, so it is independent of thread count, and
  # two calls sharing `seed` draw the same index cases -- which is what the
  # re-simulated counterfactual needs, since it pairs a factual and a flipped
  # run under CRN.
  seeds <- if (isTRUE(random_seeds)) integer(0)
           else seq_len(min(I_ini, n)) - 1L   # matches run_stoch_network's I_ini
  n_seed_draw <- if (isTRUE(random_seeds)) as.integer(min(I_ini, n)) else 0L
  # An unset seed must still move with the ambient RNG, or every call in a
  # fit would reuse one stream; drawing it here also keeps set.seed() control.
  if (is.null(seed)) seed <- sample.int(.Machine$integer.max, 1L)

  inf <- .net_sir_env$net_sir_event_times(
    n = as.integer(n), nbr = csr$nbr, ptr = csr$ptr,
    susceptibility = as.numeric(sus), transmissibility = as.numeric(tr),
    beta = as.numeric(N * beta / k_mean), gamma = as.numeric(gamma),
    t_max = as.numeric(max(timepoints)),
    seeds = as.integer(seeds), n_seed = n_seed_draw, n_sim = as.integer(n_sim),
    seed = as.integer(seed), n_threads = as.integer(cores))

  # Drop the index cases from the counts. With random seeding R does not know
  # which nodes were chosen in each realisation, but it does not need to: a seed
  # is infected at exactly t = 0, and every transmission time is continuous and
  # strictly positive, so inf == 0 identifies the seeds and nothing else.
  if (!count_seeds) {
    if (length(seeds)) inf[, seeds + 1L] <- Inf else inf[inf == 0] <- Inf
  }

  # Raw [n_sim, n] infection times: what a per-individual analysis (the EATE)
  # needs, since P_i(t) = mean(inf[, i] <= t). Aggregating to C1/C2 here would
  # throw that away.
  if (return_times) return(inf)

  is_vac <- logical(n); is_vac[vac] <- TRUE
  data.table::rbindlist(lapply(timepoints, function(tp) {
    hit <- inf <= tp                          # [n_sim, n] cumulative incidence
    data.table::data.table(
      time = tp, sim = seq_len(n_sim),
      C1 = as.numeric(rowSums(hit[, !is_vac, drop = FALSE])),
      C2 = as.numeric(rowSums(hit[,  is_vac, drop = FALSE])))
  }))
}
